[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600

lib_deps =
    4-20ma/ModbusMaster @ ^2.0.1
    arduino-libraries/NTPClient @ ^3.2.1
    rupakpoddar/ESP32Firebase @ ^1.0.0
    bblanchon/ArduinoJson @ ^6.21.3
